### ISSUE TITLE
Remove Guzzle dependency

### ISSUE THREAD

**Issue by ithielnor** [ownerrez/orez-api-php#8]
This has caused numerous problems for consumers of this library, including our own WordPress plugin. We should be able to move away from guzzle with file_get_contents or curl if we keep it simple. 

Need to resolve here first, then update our WP plugin with the latest version of this lib.

## Task

- [x] Remove the Guzzle dependency from this project
  - [x] Replace with `file_get_contents`
  - [x] Replace with optional `curl` extension
- [x] Release a new version (should be minor or patch I think) to packagist
- [x] Upgrade our WP plugin to the latest version of this library and remove the guzzle dependency from that too
  - [x] Add "Clear Cache" admin button (under Advanced Settings)
  - [x] Release a new version of the WP plugin (create a Release in GH and let the actions do the rest)

**Comment by eesquibel** [comment]
@ithielnor I still need to test w/ the WordPress plugin.

Do you have the login for our `packagist` account? Nothing comes up when I search keeper.

If you can add me as a contributor, I created an account under `eesquibel404` / `eric@ownerrez.com`

**Comment by eesquibel** [comment]
![image](https://github.com/user-attachments/assets/fc0651a7-9a7e-416a-aad5-0ed3a4878f8f)

![image](https://github.com/user-attachments/assets/c948f557-3d95-4cd8-9410-8b17bdaeb440)

**Comment by eesquibel** [comment]
Note there is also ownerrez/orez-wp#10
